name: Build and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile-server:
    name: Compile server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Compile server
        run: |
          git reset --hard
          git config --global user.email ${{ secrets.GIT_USER }}@gmail.com
          git config --global user.name ${{ secrets.GIT_USER }}
          git fetch --all
          git checkout -f server
          go build -o bin/server server.go
          if ! git diff --quiet -- bin/server; then
            git add bin/server
            git commit -m "build(compile): compile for server"
            git push origin server
          fi

  compile-clients:
    name: Compile clients
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Build Docker Image
        run: |
          docker build -t fyne-custom -f build/Dockerfile .

      - name: Compile for Windows
        run: |
          git reset --hard
          git config --global user.email ${{ secrets.GIT_USER }}@gmail.com
          git config --global user.name ${{ secrets.GIT_USER }}
          git fetch --all
          git checkout -b windows-wip
          go install github.com/fyne-io/fyne-cross@latest
          go mod tidy
          rm server.go 2>/dev/null
          fyne-cross windows -image fyne-custom
          if ! git diff --quiet -- /dist/windows-amd64/; then
            git ls-files | xargs git rm --cached
            mv fyne-cross/dist/windows-amd64/Deskor.exe.zip Deskor.exe.zip
            git add Deskor.exe.zip
            git commit -m "build(compile): compile for Windows"
            git push origin -d windows
            git push origin windows-wip:windows
          fi

      - name: Compile for Linux
        run: |
          git reset --hard
          git config --global user.email ${{ secrets.GIT_USER }}@gmail.com
          git config --global user.name ${{ secrets.GIT_USER }}
          git fetch --all
          git checkout -b linux-wip
          go install github.com/fyne-io/fyne-cross@latest
          go mod tidy
          rm server.go 2>/dev/null
          fyne-cross linux -image fyne-custom
          if ! git diff --quiet -- /dist/linux-amd64/; then
            git ls-files | xargs git rm --cached
            mv fyne-cross/dist/linux-amd64/Deskor.tar.xz Deskor.tar.xz
            git add Deskor.tar.xz
            git commit -m "build(compile): compile for Linux"
            git push origin -d linux
            git push origin linux-wip:linux
          fi
