name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  compile-server:
    name: Compile server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Compile server
        run: |
          git config --global user.email ${{ secrets.GIT_USER }}@gmail.com
          git config --global user.name ${{ secrets.GIT_USER }}
          git checkout -f -b server-wip
          go build -o bin/server server.go
          git ls-files | xargs git rm --cached
          mv bin/server server
          mv .env.server.sample .env.server
          mv build/server/README.md README.md
          git add -f server .env.server README.md
          git commit -m "build(compile): compile for server"
          git push origin -d server
          git push origin server-wip:server

  compile-windows:
    name: Compile windows
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Build Docker Image
        run: |
          docker build -t fyne-custom -f build/Dockerfile .

      - name: Compile for Windows
        run: |
          git config --global user.email ${{ secrets.GIT_USER }}@gmail.com
          git config --global user.name ${{ secrets.GIT_USER }}
          git checkout -b windows-wip
          go install github.com/fyne-io/fyne-cross@latest
          go mod tidy
          rm server.go 2>/dev/null
          fyne-cross windows -image fyne-custom
          git ls-files | xargs git rm --cached
          mv fyne-cross/bin/windows-amd64/Deskor.exe Deskor.exe
          mv build/client/README.md README.md
          git add -f Deskor.exe README.md
          git commit -m "build(compile): compile for Windows"
          git push origin -d windows
          git push origin windows-wip:windows

  compile-linux:
    name: Compile linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Build Docker Image
        run: |
          docker build -t fyne-custom -f build/Dockerfile .

      - name: Compile for Linux
        run: |
          git config --global user.email ${{ secrets.GIT_USER }}@gmail.com
          git config --global user.name ${{ secrets.GIT_USER }}
          git checkout -b linux-wip
          go install github.com/fyne-io/fyne-cross@latest
          go mod tidy
          rm server.go 2>/dev/null
          fyne-cross linux -image fyne-custom
          git ls-files | xargs git rm --cached
          mv fyne-cross/bin/linux-amd64/deskor deskor
          mv build/client/README.md README.md
          git add -f deskor README.md
          git commit -m "build(compile): compile for Linux"
          git push origin -d linux
          git push origin linux-wip:linux
